@extends('layouts.app')
@section('title', 'Production Planning')
@section('content')
<div class="container-fluid px-0">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row g-4 mb-4">
        <div class="col-xl-4"><div class="card shadow-sm border-0 h-100"><div class="card-header bg-white"><strong><i class="bi bi-diagram-3 me-1"></i>Sewing line capacity</strong></div><div class="card-body">
            <form method="POST" action="{{ route('admin.sewing-lines.store') }}" class="row g-2">@csrf
                <div class="col-6"><label class="form-label">Line code</label><input name="line_code" class="form-control" required placeholder="GSV-BLUE"></div>
                <div class="col-6"><label class="form-label">Line color</label><select name="line_name" class="form-select" required><option value="">Select existing line</option>@foreach($lineColors as $color)<option value="{{ $color->name }}">{{ $color->name }} · {{ $color->cate }}</option>@endforeach</select></div>
                <div class="col-4"><label class="form-label">Workers</label><input type="number" name="default_workers" min="1" class="form-control" required></div><div class="col-4"><label class="form-label">Hours/day</label><input type="number" name="working_hours_per_day" min="0.25" step="0.25" class="form-control" value="8" required></div><div class="col-4"><label class="form-label">Labor rate</label><input type="number" name="labor_rate" min="0" step="0.01" class="form-control" value="0"></div>
                <div class="col-12"><button class="btn btn-outline-primary w-100">Add sewing line</button></div>
            </form>
            <hr><div class="small">@forelse($lines as $line)<div class="d-flex justify-content-between align-items-center border-bottom py-1"><span>{{ $line->line_code }} — {{ $line->line_name }} @if(!$line->is_active)<span class="badge bg-secondary">Inactive</span>@endif</span><span>{{ $line->default_workers }} workers · {{ $line->working_hours_per_day }}h <button type="button" class="btn btn-sm btn-outline-secondary ms-1" onclick='editLine(@json($line))'><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.sewing-lines.destroy',$line->id) }}" class="d-inline" onsubmit="return confirm('Delete this sewing line?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></span></div>@empty<span class="text-muted">No sewing lines yet.</span>@endforelse</div>
        </div></div></div>
        <div class="col-xl-4"><div class="card shadow-sm border-0 h-100"><div class="card-header bg-white"><strong><i class="bi bi-clipboard-plus me-1"></i>Create Work Order</strong></div><div class="card-body"><form method="POST" action="{{ route('admin.work-orders.store') }}" class="row g-3">@csrf
            <div class="col-12"><label class="form-label">Order Cut Sheet</label><select name="cutsheet_id" class="form-select" required><option value="">Select CS</option>@foreach($orders as $order)<option value="{{ $order->id }}">{{ $order->CS }} · {{ $order->SNo }} · Qty {{ $order->Qty }}</option>@endforeach</select></div><div class="col-6"><label class="form-label">Planned Qty</label><input type="number" name="planned_qty" min="1" class="form-control" required></div><div class="col-6"><label class="form-label">SMV (minutes)</label><input type="number" name="smv" min="0.01" step="0.01" class="form-control" required></div><div class="col-12"><button class="btn btn-primary w-100">Create Work Order</button></div>
        </form></div></div></div>
        <div class="col-xl-4"><div class="card shadow-sm border-0 h-100"><div class="card-header bg-white"><strong><i class="bi bi-calendar-plus me-1"></i>Create MPS Schedule</strong></div><div class="card-body"><form method="POST" action="{{ route('admin.mps-schedules.store') }}" class="row g-2">@csrf
            <div class="col-12"><label class="form-label">Work Order</label><select name="work_order_id" class="form-select" required><option value="">Select work order</option>@foreach($workOrders as $wo)<option value="{{ $wo->id }}">{{ $wo->wo_number }} · {{ $wo->CS }} · Qty {{ $wo->planned_qty }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Sewing line</label><select name="line_id" class="form-select" required><option value="">Select line</option>@foreach($lines->where('is_active', true) as $line)<option value="{{ $line->id }}">{{ $line->line_code }} — {{ $line->line_name }}</option>@endforeach</select></div><div class="col-6"><label class="form-label">Start</label><input type="date" name="planned_start_date" class="form-control" required></div><div class="col-6"><label class="form-label">End</label><input type="date" name="planned_end_date" class="form-control" required></div><div class="col-12"><label class="form-label">Daily target qty</label><input type="number" name="daily_target_qty" min="1" class="form-control" required></div><div class="col-12"><button class="btn btn-success w-100">Validate & create schedule</button></div>
        </form></div></div></div>
    </div>
    <div class="card shadow-sm border-0 mb-4"><div class="card-header bg-white"><strong>Work Orders</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>WO</th><th>CS / Style</th><th>Qty</th><th>SMV</th><th>Status</th><th>Split</th></tr></thead><tbody>@forelse($workOrders as $wo)<tr><td class="fw-semibold">{{ $wo->wo_number }}</td><td>{{ $wo->CS }} / {{ $wo->SNo }}</td><td>{{ $wo->planned_qty }} / {{ $wo->order_qty }}</td><td>{{ $wo->smv }}</td><td><form method="POST" action="{{ route('admin.work-orders.status',$wo->id) }}">@csrf @method('PATCH')<select name="status" class="form-select form-select-sm" onchange="this.form.submit()" {{ in_array($wo->status,['completed','cancelled']) ? 'disabled' : '' }}>@foreach(['planned','released','in_production','completed','cancelled'] as $status)<option value="{{ $status }}" @selected($wo->status===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></form></td><td>@if($wo->status==='planned')<form method="POST" action="{{ route('admin.work-orders.split',$wo->id) }}" class="d-flex gap-1">@csrf<input name="planned_qty" type="number" min="1" max="{{ $wo->planned_qty - 1 }}" class="form-control form-control-sm" style="width:90px" required><button class="btn btn-sm btn-outline-primary">Split</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-3">No work orders yet.</td></tr>@endforelse</tbody></table></div></div>
    <div class="card shadow-sm border-0"><div class="card-header bg-white"><strong>MPS Schedules</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Work Order</th><th>CS</th><th>Line</th><th>Period</th><th>Daily target</th><th>SMV</th><th>Material</th><th></th></tr></thead><tbody>@forelse($schedules as $schedule)<tr><td>{{ $schedule->wo_number }}</td><td>{{ $schedule->CS }}</td><td>{{ $schedule->line_code }} — {{ $schedule->line_name }}</td><td>{{ $schedule->planned_start_date }} → {{ $schedule->planned_end_date }}</td><td>{{ $schedule->daily_target_qty }}</td><td>{{ $schedule->smv }}</td><td><span class="badge bg-{{ $schedule->material_eta_status==='ready'?'success':'secondary' }}">{{ $schedule->material_eta_status }}</span></td><td class="text-end"><button type="button" class="btn btn-sm btn-outline-warning" onclick='editSchedule(@json($schedule))'><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.mps-schedules.destroy',$schedule->id) }}" class="d-inline" onsubmit="return confirm('Delete this schedule?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-3">No schedules yet.</td></tr>@endforelse</tbody></table></div></div>
</div>
<div class="modal fade" id="lineModal"><div class="modal-dialog"><form method="POST" id="lineForm" class="modal-content">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Edit sewing line</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Line code</label><input id="editLineCode" name="line_code" class="form-control" required></div><div class="col-md-6"><label class="form-label">Line name</label><input id="editLineName" name="line_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Workers</label><input id="editLineWorkers" type="number" min="1" name="default_workers" class="form-control" required></div><div class="col-md-4"><label class="form-label">Hours/day</label><input id="editLineHours" type="number" min="0.25" step="0.25" name="working_hours_per_day" class="form-control" required></div><div class="col-md-4"><label class="form-label">Labor rate</label><input id="editLineRate" type="number" min="0" step="0.01" name="labor_rate" class="form-control"></div><div class="col-12"><label class="form-label">Status</label><select id="editLineActive" name="is_active" class="form-select"><option value="1">Active</option><option value="0">Inactive</option></select></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save changes</button></div></form></div></div>
<div class="modal fade" id="scheduleModal"><div class="modal-dialog"><form method="POST" id="scheduleForm" class="modal-content">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Edit MPS schedule</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Sewing line</label><select id="editScheduleLine" name="line_id" class="form-select" required>@foreach($lines->where('is_active', true) as $line)<option value="{{ $line->id }}">{{ $line->line_code }} — {{ $line->line_name }}</option>@endforeach</select></div><div class="col-6"><label class="form-label">Start</label><input id="editScheduleStart" type="date" name="planned_start_date" class="form-control" required></div><div class="col-6"><label class="form-label">End</label><input id="editScheduleEnd" type="date" name="planned_end_date" class="form-control" required></div><div class="col-12"><label class="form-label">Daily target qty</label><input id="editScheduleTarget" type="number" min="1" name="daily_target_qty" class="form-control" required></div></div></div><div class="modal-footer"><button class="btn btn-primary">Validate &amp; save</button></div></form></div></div>
@endsection
@push('scripts')<script>function editLine(line){document.getElementById('lineForm').action='{{ url('admin/sewing-lines') }}/'+line.id;document.getElementById('editLineCode').value=line.line_code;document.getElementById('editLineName').value=line.line_name;document.getElementById('editLineWorkers').value=line.default_workers;document.getElementById('editLineHours').value=line.working_hours_per_day;document.getElementById('editLineRate').value=line.labor_rate;document.getElementById('editLineActive').value=Number(line.is_active);new bootstrap.Modal(document.getElementById('lineModal')).show();}function editSchedule(schedule){document.getElementById('scheduleForm').action='{{ url('admin/mps-schedules') }}/'+schedule.id;document.getElementById('editScheduleLine').value=schedule.line_id;document.getElementById('editScheduleStart').value=schedule.planned_start_date;document.getElementById('editScheduleEnd').value=schedule.planned_end_date;document.getElementById('editScheduleTarget').value=schedule.daily_target_qty;new bootstrap.Modal(document.getElementById('scheduleModal')).show();}</script>@endpush
