@extends('layouts.app')
@section('title', 'Shop Floor Downtime')
@section('content')
<div class="container-fluid px-0">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-4"><div class="col-lg-4"><div class="card shadow-sm border-0"><div class="card-header bg-white"><strong><i class="bi bi-stopwatch me-2"></i>Record downtime</strong></div><div class="card-body"><form method="POST" action="{{ route('admin.shopfloor.downtime.store') }}" class="row g-3">@csrf
<div class="col-12"><label class="form-label">Sewing line *</label><select name="line_id" class="form-select" required><option value="">Select line</option>@foreach($lines as $line)<option value="{{ $line->id }}" @selected(old('line_id')==$line->id)>{{ $line->line_code }} — {{ $line->line_name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Date *</label><input type="date" max="{{ now()->toDateString() }}" name="log_date" value="{{ old('log_date',now()->toDateString()) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Minutes *</label><input type="number" min="1" max="1440" name="downtime_minutes" value="{{ old('downtime_minutes') }}" class="form-control" required></div><div class="col-12"><label class="form-label">Reason *</label><textarea name="reason" rows="3" class="form-control" required>{{ old('reason') }}</textarea></div><div class="col-12"><button class="btn btn-warning w-100">Save downtime</button></div>
</form></div></div></div>
<div class="col-lg-8"><div class="card shadow-sm border-0"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Downtime history</strong><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.shopfloor.dashboard') }}">Shop Floor Dashboard</a></div><div class="card-body border-bottom"><form method="GET" class="row g-2"><div class="col-md-5"><select name="line_id" class="form-select"><option value="">All lines</option>@foreach($lines as $line)<option value="{{ $line->id }}" @selected(request('line_id')==$line->id)>{{ $line->line_code }} — {{ $line->line_name }}</option>@endforeach</select></div><div class="col-md-4"><input type="date" name="date" value="{{ request('date') }}" class="form-control"></div><div class="col-md-3"><button class="btn btn-dark">Filter</button><a href="{{ route('admin.shopfloor.downtime') }}" class="btn btn-outline-secondary">Reset</a></div></form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Date</th><th>Line</th><th class="text-end">Minutes</th><th>Reason</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->log_date }}</td><td>{{ $log->line_code }} — {{ $log->line_name }}</td><td class="text-end fw-bold">{{ $log->downtime_minutes }}</td><td>{{ $log->reason }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">No downtime logs.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $logs->links() }}</div></div></div></div>
</div>
@endsection
