@extends('layouts.app')
@section('title', 'Customer Master')
@section('content')
<div class="container-fluid px-0">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="card shadow-sm border-0 mb-4"><div class="card-body d-flex justify-content-between align-items-center"><div><h5 class="mb-1 fw-bold"><i class="bi bi-people me-2"></i>Customer Master</h5><small class="text-muted">Customer records can be selected when creating or editing an OCS.</small></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#customerModal"><i class="bi bi-plus-lg"></i> Add customer</button></div></div>
    <form method="GET" class="d-flex gap-2 mb-3"><input name="search" value="{{ request('search') }}" class="form-control" style="max-width:320px" placeholder="Search name or brand"><button class="btn btn-dark">Search</button><a class="btn btn-outline-secondary" href="{{ route('admin.master-data.customers') }}">Reset</a></form>
    <div class="card shadow-sm border-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Name</th><th>Brand</th><th>Contact</th><th>Phone</th><th>Email</th><th>Address</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($customers as $customer)<tr><td class="fw-semibold">{{ $customer->name }}</td><td>{{ $customer->brand ?: '-' }}</td><td>{{ $customer->contact ?: '-' }}</td><td>{{ $customer->tel ?: '-' }}</td><td>{{ $customer->email ?: '-' }}</td><td><small>{{ $customer->address ?: '-' }}</small></td><td class="text-end"><button type="button" class="btn btn-sm btn-warning" onclick='editCustomer(@json($customer))'><i class="bi bi-pencil"></i></button><form class="d-inline" method="POST" action="{{ route('admin.master-data.customers.destroy',$customer->id) }}" onsubmit="return confirm('Delete this customer?')">@csrf @method('DELETE')<button class="btn btn-sm btn-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No customers yet.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $customers->links() }}</div></div>
</div>
<div class="modal fade" id="customerModal" tabindex="-1"><div class="modal-dialog"><form method="POST" id="customerForm" action="{{ route('admin.master-data.customers.store') }}" class="modal-content">@csrf <div id="customerMethod"></div><div class="modal-header"><h5 class="modal-title" id="customerModalTitle">Add customer</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Name *</label><input name="name" id="customerName" class="form-control" required></div><div class="col-md-6"><label class="form-label">Brand</label><input name="brand" id="customerBrand" class="form-control"></div><div class="col-md-6"><label class="form-label">Contact</label><input name="contact" id="customerContact" class="form-control"></div><div class="col-md-6"><label class="form-label">Phone</label><input name="tel" id="customerTel" class="form-control"></div><div class="col-12"><label class="form-label">Email</label><input type="email" name="email" id="customerEmail" class="form-control"></div><div class="col-12"><label class="form-label">Address</label><textarea name="address" id="customerAddress" class="form-control" rows="2"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save customer</button></div></form></div></div>
@push('scripts')<script>function editCustomer(c){const f=document.getElementById('customerForm');f.action='{{ url('admin/master-data/customers') }}/'+c.id;document.getElementById('customerMethod').innerHTML='@method("PATCH")';document.getElementById('customerModalTitle').textContent='Edit customer';for(const [id,key] of Object.entries({customerName:'name',customerBrand:'brand',customerContact:'contact',customerTel:'tel',customerEmail:'email',customerAddress:'address'})){document.getElementById(id).value=c[key]||'';}new bootstrap.Modal(document.getElementById('customerModal')).show();}</script>@endpush
@endsection
