@extends('layouts.app')
@section('title', 'Material Master')
@section('content')
<div class="container-fluid px-0">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card shadow-sm border-0 mb-4"><div class="card-body d-flex justify-content-between align-items-center"><div><h5 class="mb-1 fw-bold"><i class="bi bi-box-seam me-2"></i>Material Master</h5><small class="text-muted">Standard material data used by BOM, MRP, inventory and purchasing.</small></div><div class="d-flex gap-2"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#mappingModal">Map supplier</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#materialModal">Add material</button></div></div></div>
<form method="GET" class="d-flex gap-2 mb-3"><input name="search" value="{{ request('search') }}" class="form-control" style="max-width:320px" placeholder="Code or material name"><button class="btn btn-dark">Search</button><a class="btn btn-outline-secondary" href="{{ route('admin.master-data.materials') }}">Reset</a></form>
<div class="card shadow-sm border-0 mb-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Code</th><th>Name</th><th>Type</th><th>Color / Size</th><th>Unit</th><th>Suppliers</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($materials as $material)<tr><td><code>{{ $material->internal_code }}</code></td><td class="fw-semibold">{{ $material->material_name }}</td><td><span class="badge bg-info">{{ $material->material_type }}</span></td><td>{{ $material->color ?: '-' }} / {{ $material->size ?: '-' }}</td><td>{{ $material->unit }}</td><td>{{ $material->vendor_count }}</td><td class="text-end"><button class="btn btn-sm btn-warning" onclick='editMaterial(@json($material))'><i class="bi bi-pencil"></i></button></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No materials yet.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $materials->links() }}</div></div>
<div class="card shadow-sm border-0"><div class="card-header bg-white"><strong>Material–supplier mappings</strong></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th>Material</th><th>Supplier</th><th>Supplier item code</th><th class="text-end">Unit price</th><th class="text-end">Lead time</th><th>Default</th><th></th></tr></thead><tbody>@forelse($vendorMappings as $map)<tr><td><code>{{ $map->internal_code }}</code> {{ $map->material_name }}</td><td>{{ $map->supplier_code }} — {{ $map->supplier_name }}</td><td>{{ $map->vendor_item_code ?: '-' }}</td><td class="text-end">{{ number_format($map->unit_price,2) }}</td><td class="text-end">{{ $map->lead_time_days }} days</td><td>{!! $map->is_default_vendor ? '<span class="badge bg-success">Default</span>' : '-' !!}</td><td class="text-end"><form method="POST" action="{{ route('admin.master-data.material-vendors.destroy',$map->id) }}" onsubmit="return confirm('Remove this mapping?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-3">No mappings yet.</td></tr>@endforelse</tbody></table></div></div>
</div>
<div class="modal fade" id="materialModal"><div class="modal-dialog"><form id="materialForm" method="POST" action="{{ route('admin.master-data.materials.store') }}" class="modal-content">@csrf <div id="materialMethod"></div><div class="modal-header"><h5 class="modal-title" id="materialModalTitle">Add material</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Internal code *</label><input id="materialCode" name="internal_code" class="form-control" required></div><div class="col-md-6"><label class="form-label">Type *</label><select id="materialType" name="material_type" class="form-select">@foreach(['fabric','lining','pocket','trim','thread','zipper','label','elastic','interlining','other'] as $type)<option value="{{ $type }}">{{ ucfirst($type) }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Name *</label><input id="materialName" name="material_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Color</label><input id="materialColor" name="color" class="form-control"></div><div class="col-md-4"><label class="form-label">Size</label><input id="materialSize" name="size" class="form-control"></div><div class="col-md-4"><label class="form-label">Unit *</label><input id="materialUnit" name="unit" value="M" class="form-control" required></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save material</button></div></form></div></div>
<div class="modal fade" id="mappingModal"><div class="modal-dialog"><form method="POST" action="{{ route('admin.master-data.material-vendors.store') }}" class="modal-content">@csrf <div class="modal-header"><h5 class="modal-title">Map material to supplier</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Material *</label><select name="material_id" class="form-select" required><option value="">Select material</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->internal_code }} — {{ $material->material_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Supplier *</label><select name="vendor_id" class="form-select" required><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->code }} — {{ $supplier->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Supplier item code</label><input name="vendor_item_code" class="form-control"></div><div class="col-md-6"><label class="form-label">Unit price *</label><input type="number" min="0" step="0.01" name="unit_price" value="0" class="form-control" required></div><div class="col-md-6"><label class="form-label">Lead time (days) *</label><input type="number" min="0" name="lead_time_days" value="0" class="form-control" required></div><div class="col-md-6 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" value="1" name="is_default_vendor" id="defaultVendor"><label class="form-check-label" for="defaultVendor">Default supplier</label></div></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save mapping</button></div></form></div></div>
@push('scripts')<script>function editMaterial(m){const f=document.getElementById('materialForm');f.action='{{ url('admin/master-data/materials') }}/'+m.id;document.getElementById('materialMethod').innerHTML='@method("PATCH")';document.getElementById('materialModalTitle').textContent='Edit material';for(const [id,key] of Object.entries({materialCode:'internal_code',materialName:'material_name',materialColor:'color',materialSize:'size',materialUnit:'unit',materialType:'material_type'})){document.getElementById(id).value=m[key]||'';}new bootstrap.Modal(document.getElementById('materialModal')).show();}</script>@endpush
@endsection
