@extends('layouts.app')
@section('title', 'Material Master')
@section('content')
<div class="card shadow-sm border-0 mb-4"><div class="card-body d-flex justify-content-between align-items-center">
 <div><h5 class="mb-1 fw-bold"><i class="bi bi-box-seam me-2"></i>Material Master</h5><small class="text-muted">Standard material data used by BOM, MRP, inventory and purchasing.</small></div>
 <div class="d-flex gap-2"><button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#taxonomyModal">Manage categories</button><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#mappingModal">Map supplier</button><button class="btn btn-primary" onclick="newMaterial()">Add material</button></div>
</div></div>
<form method="GET" class="d-flex gap-2 mb-3"><input name="search" value="{{ request('search') }}" class="form-control" style="max-width:320px" placeholder="Code or material name"><button class="btn btn-dark">Search</button><a class="btn btn-outline-secondary" href="{{ route('admin.master-data.materials') }}">Reset</a></form>
<div class="card shadow-sm border-0 mb-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
 <thead class="table-light"><tr><th>Code</th><th>Name</th><th>Category</th><th>Subcategory</th><th>Color / Size</th><th>Unit</th><th>Suppliers</th><th class="text-end">Action</th></tr></thead>
 <tbody>@forelse($materials as $material)<tr><td><code>{{ $material->internal_code }}</code></td><td class="fw-semibold">{{ $material->material_name }}</td><td><span class="badge bg-info">{{ $material->category_name ?: ucfirst($material->material_type) }}</span></td><td>{{ $material->subcategory_name ?: '-' }}</td><td>{{ $material->color ?: '-' }} / {{ $material->size ?: '-' }}</td><td>{{ $material->unit }}</td><td>{{ $material->vendor_count }}</td><td class="text-end"><button class="btn btn-sm btn-warning" onclick='editMaterial(@json($material))'><i class="bi bi-pencil"></i></button></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No materials yet.</td></tr>@endforelse</tbody>
</table></div><div class="card-footer">{{ $materials->links() }}</div></div>
<div class="card shadow-sm border-0"><div class="card-header fw-bold">Material–supplier mappings</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Material</th><th>Supplier</th><th>Supplier item code</th><th>Unit price</th><th>Lead time</th><th>Default</th><th></th></tr></thead><tbody>
 @forelse($vendorMappings as $mapping)<tr><td>{{ $mapping->internal_code }} — {{ $mapping->material_name }}</td><td>{{ $mapping->supplier_code }} — {{ $mapping->supplier_name }}</td><td>{{ $mapping->vendor_item_code ?: '-' }}</td><td>{{ number_format($mapping->unit_price, 2) }}</td><td>{{ $mapping->lead_time_days }} days</td><td>{{ $mapping->is_default_vendor ? 'Yes' : 'No' }}</td><td><form method="POST" action="{{ route('admin.master-data.material-vendors.destroy', $mapping->id) }}" onsubmit="return confirm('Delete this mapping?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-3">No mappings yet.</td></tr>@endforelse
</tbody></table></div></div>

<div class="modal fade" id="materialModal"><div class="modal-dialog"><form id="materialForm" method="POST" action="{{ route('admin.master-data.materials.store') }}" class="modal-content">@csrf<div id="materialMethod"></div>
 <div class="modal-header"><h5 class="modal-title" id="materialModalTitle">Add material</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
  <div class="col-md-6"><label class="form-label">Internal code *</label><input id="materialCode" name="internal_code" class="form-control" required></div>
  <div class="col-md-6"><label class="form-label">Category *</label><select id="materialCategory" name="category_id" class="form-select" required onchange="filterSubcategories()"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label">Subcategory</label><select id="materialSubcategory" name="subcategory_id" class="form-select"><option value="">No subcategory</option>@foreach($subcategories as $subcategory)<option value="{{ $subcategory->id }}" data-category="{{ $subcategory->category_id }}">{{ $subcategory->name }}</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label">Name *</label><input id="materialName" name="material_name" class="form-control" required></div>
  <div class="col-md-4"><label class="form-label">Color</label><input id="materialColor" name="color" class="form-control"></div><div class="col-md-4"><label class="form-label">Size</label><input id="materialSize" name="size" class="form-control"></div><div class="col-md-4"><label class="form-label">Unit *</label><input id="materialUnit" name="unit" value="M" class="form-control" required></div>
 </div></div><div class="modal-footer"><button class="btn btn-primary">Save material</button></div>
</form></div></div>

<div class="modal fade" id="taxonomyModal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Manage categories</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-4">
 <div class="col-md-6"><h6>Categories</h6><form method="POST" action="{{ route('admin.master-data.material-categories.store') }}" class="input-group mb-3">@csrf<input name="name" class="form-control" placeholder="New category" required><button class="btn btn-primary">Add</button></form>
 @forelse($categories as $category)<div class="border rounded p-2 mb-2 d-flex gap-2"><form method="POST" action="{{ route('admin.master-data.material-categories.update', $category->id) }}" class="d-flex gap-2 flex-grow-1">@csrf @method('PATCH')<input name="name" value="{{ $category->name }}" class="form-control form-control-sm" required><button class="btn btn-sm btn-outline-primary"><i class="bi bi-check-lg"></i></button></form><form method="POST" action="{{ route('admin.master-data.material-categories.destroy', $category->id) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div>@empty<p class="text-muted">No categories yet.</p>@endforelse</div>
 <div class="col-md-6"><h6>Subcategories</h6><form method="POST" action="{{ route('admin.master-data.material-subcategories.store') }}" class="input-group mb-3">@csrf<select name="category_id" class="form-select" required><option value="">Category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input name="name" class="form-control" placeholder="New subcategory" required><button class="btn btn-primary">Add</button></form>
 @forelse($subcategories as $subcategory)<div class="border rounded p-2 mb-2"><form method="POST" action="{{ route('admin.master-data.material-subcategories.update', $subcategory->id) }}" class="d-flex gap-2">@csrf @method('PATCH')<select name="category_id" class="form-select form-select-sm" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($subcategory->category_id == $category->id)>{{ $category->name }}</option>@endforeach</select><input name="name" value="{{ $subcategory->name }}" class="form-control form-control-sm" required><button class="btn btn-sm btn-outline-primary"><i class="bi bi-check-lg"></i></button></form><form method="POST" action="{{ route('admin.master-data.material-subcategories.destroy', $subcategory->id) }}" class="text-end mt-1" onsubmit="return confirm('Delete this subcategory?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div>@empty<p class="text-muted">No subcategories yet.</p>@endforelse</div>
</div></div></div></div></div>

<div class="modal fade" id="mappingModal"><div class="modal-dialog"><form method="POST" action="{{ route('admin.master-data.material-vendors.store') }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">Map material to supplier</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
 <div class="col-12"><label class="form-label">Material *</label><select name="material_id" class="form-select" required><option value="">Select material</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->internal_code }} — {{ $material->material_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Supplier *</label><select name="vendor_id" class="form-select" required><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->code }} — {{ $supplier->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Supplier item code</label><input name="vendor_item_code" class="form-control"></div><div class="col-md-6"><label class="form-label">Unit price *</label><input type="number" min="0" step="0.01" name="unit_price" value="0" class="form-control" required></div><div class="col-md-6"><label class="form-label">Lead time (days) *</label><input type="number" min="0" name="lead_time_days" value="0" class="form-control" required></div><div class="col-md-6 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" value="1" name="is_default_vendor" id="defaultVendor"><label class="form-check-label" for="defaultVendor">Default supplier</label></div></div>
 </div></div><div class="modal-footer"><button class="btn btn-primary">Save mapping</button></div></form></div></div>
@endsection
@push('scripts')
<script>
function filterSubcategories(selected=''){const category=document.getElementById('materialCategory').value,select=document.getElementById('materialSubcategory');[...select.options].forEach((o,i)=>{if(i)o.hidden=o.dataset.category!==category});if(selected&&[...select.options].some(o=>o.value==selected&&!o.hidden))select.value=selected;else if(select.selectedOptions[0]?.hidden)select.value=''}
function newMaterial(){const f=document.getElementById('materialForm');f.reset();f.action=@json(route('admin.master-data.materials.store'));document.getElementById('materialMethod').innerHTML='';document.getElementById('materialModalTitle').textContent='Add material';document.getElementById('materialUnit').value='M';filterSubcategories();bootstrap.Modal.getOrCreateInstance(document.getElementById('materialModal')).show()}
function editMaterial(m){const f=document.getElementById('materialForm');f.action=@json(url('admin/master-data/materials'))+'/'+m.id;document.getElementById('materialMethod').innerHTML='<input type="hidden" name="_method" value="PATCH">';document.getElementById('materialModalTitle').textContent='Edit material';for(const [id,key] of Object.entries({materialCode:'internal_code',materialName:'material_name',materialColor:'color',materialSize:'size',materialUnit:'unit',materialCategory:'category_id'}))document.getElementById(id).value=m[key]||'';filterSubcategories(m.subcategory_id||'');bootstrap.Modal.getOrCreateInstance(document.getElementById('materialModal')).show()}
</script>
@endpush
