@extends('layouts.app')
@section('title', 'Edit Master Plan')
@section('content')
@php $fabricOnly=$fabricOnly??false; $updateRoute=$updateRoute??route('admin.masterplan.update',$plan->id); $readonly=$fabricOnly?'readonly':''; @endphp
<div class="container-fluid px-0">
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<form method="POST" action="{{ $updateRoute }}">@csrf @method('PUT')
<div class="card shadow-sm border-0 mb-4"><div class="card-header bg-white py-3"><h5 class="mb-0 fw-bold"><i class="bi bi-info-circle me-2"></i>Order & Line Info</h5></div><div class="card-body"><div class="row g-3">
<div class="col-md-4"><label class="form-label">CU (CS)</label><input name="CU" class="form-control" value="{{ $plan->CU }}" readonly></div><div class="col-md-3"><label class="form-label">PO</label><input class="form-control" value="{{ $plan->PO }}" readonly></div><div class="col-md-3"><label class="form-label">Style</label><input class="form-control" value="{{ $plan->Style }}" readonly></div><div class="col-md-2"><label class="form-label">OCS Qty</label><input class="form-control" value="{{ $plan->Qty??'-' }}" readonly></div>
<div class="col-md-4"><label class="form-label">Line</label>@if($fabricOnly)<input name="Line" class="form-control" value="{{ old('Line',$plan->Line) }}" readonly>@else<select name="Line" id="lineSelect" class="form-select" required><option value="">-- Select Line --</option>@foreach(($colors??collect()) as $lineColor)<option value="{{ $lineColor->name }}" data-hex="{{ $lineColor->hex_code }}" {{ old('Line',$plan->Line)===$lineColor->name?'selected':'' }}>{{ $lineColor->name }}</option>@endforeach</select>@endif</div>
<div class="col-md-4"><label class="form-label">Line Color</label><div class="input-group"><input type="hidden" name="LineColor" id="lineColorInput" value="{{ old('LineColor',$plan->LineColor??'#808080') }}"><span class="input-group-text"><span id="lineColorSwatch" style="display:block;width:28px;height:28px;border-radius:4px;background:#808080"></span></span><input id="lineColorText" class="form-control" value="{{ old('LineColor',$plan->LineColor??'#808080') }}" readonly></div></div>
<div class="col-md-2"><label class="form-label">LT (days)</label><input type="number" name="lt" class="form-control" min="0" value="{{ old('lt',$plan->lt) }}" {{ $readonly }}></div><div class="col-md-3"><label class="form-label">Qty_dis</label><input type="number" name="Qty_dis" class="form-control" min="0" value="{{ old('Qty_dis',$plan->Qty_dis) }}" {{ $readonly }}>@error('Qty_dis')<div class="text-danger">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label">ExQty</label><input type="number" name="ExQty" class="form-control" min="0" value="{{ old('ExQty',$plan->ExQty) }}" {{ $readonly }}></div><div class="col-md-3"><label class="form-label">FirstOPT</label><input type="date" name="FirstOPT" class="form-control" value="{{ old('FirstOPT',$plan->FirstOPT?\Carbon\Carbon::parse($plan->FirstOPT)->format('Y-m-d'):'') }}" {{ $readonly }}></div>
</div></div></div>
<div class="card shadow-sm border-0 mb-4"><div class="card-header bg-white py-3"><h5 class="mb-0 fw-bold"><i class="bi bi-calendar-check me-2"></i>MPS Planning</h5></div><div class="card-body"><div class="row g-3">
<div class="col-md-3"><label class="form-label">MPS Status</label><select name="mps_status" class="form-select" {{ $fabricOnly?'disabled':'' }}>@foreach(['planned'=>'Planned','in_production'=>'In Production','completed'=>'Completed','on_hold'=>'On Hold'] as $value=>$label)<option value="{{ $value }}" {{ old('mps_status',$plan->mps_status??'planned')===$value?'selected':'' }}>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Priority</label><select name="mps_priority" class="form-select" {{ $fabricOnly?'disabled':'' }}>@foreach(['low'=>'Low','medium'=>'Medium','high'=>'High','urgent'=>'Urgent'] as $value=>$label)<option value="{{ $value }}" {{ old('mps_priority',$plan->mps_priority??'medium')===$value?'selected':'' }}>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Daily Target Qty</label><input type="number" name="daily_target_qty" class="form-control" min="0" value="{{ old('daily_target_qty',$plan->daily_target_qty) }}" {{ $readonly }}></div>
@foreach(['Require_date'=>'Require Date','Confirm_date'=>'Confirm Date','planned_cut_start'=>'Planned Cut Start','planned_cut_end'=>'Planned Cut End','planned_sew_start'=>'Planned Sew Start','planned_sew_end'=>'Planned Sew End'] as $field=>$label)<div class="col-md-3"><label class="form-label">{{ $label }}</label><input type="date" name="{{ $field }}" class="form-control" value="{{ old($field,$plan->$field) }}" {{ $readonly }}></div>@endforeach
</div></div></div>
<div class="card shadow-sm border-0 mb-4"><div class="card-header bg-white py-3"><h5 class="mb-0 fw-bold"><i class="bi bi-box-seam me-2"></i>Materials & Supply Chain</h5></div><div class="card-body"><div class="row g-3">
@foreach([['Fabric1','Fabric 1','text','col-md-4'],['ETA1','ETA 1','date','col-md-2'],['Actual','Actual','date','col-md-2'],['Fabric2','Fabric 2','text','col-md-4'],['ETA2','ETA 2','date','col-md-2'],['Linning','Lining','text','col-md-4'],['ETA3','ETA 3','date','col-md-2'],['Pocket','Pocket','text','col-md-4'],['ETA4','ETA 4','date','col-md-2'],['Trim','Trim','text','col-md-4'],['Norm_date','Norm Date','date','col-md-3'],['inWHDate','In-Warehouse Date','date','col-md-3'],['3rd_PartyInspection','3rd Party Inspection','text','col-md-3'],['ShipDate2','Ship Date','date','col-md-3'],['SoTK','SoTK','text','col-md-3']] as [$field,$label,$type,$column])<div class="{{ $column }}"><label class="form-label">{{ $label }}</label><input type="{{ $type }}" name="{{ $field }}" class="form-control" value="{{ old($field,$plan->$field??'') }}" {{ $readonly }}></div>@endforeach
<div class="col-12"><label class="form-label">Notes</label><textarea name="mps_notes" class="form-control" rows="2" {{ $readonly }}>{{ old('mps_notes',$plan->mps_notes??'') }}</textarea></div>
</div></div></div>
<div class="d-flex gap-2 mb-4"><a href="{{ $fabricOnly?route('masterplan.view'):route('admin.masterplan.index') }}" class="btn btn-secondary px-4">Cancel</a><button class="btn btn-primary px-4"><i class="bi bi-save me-1"></i>{{ $fabricOnly?'Update Fabric-Trim':'Update Master Plan' }}</button></div>
</form></div>
<script>const s=document.getElementById('lineSelect'),i=document.getElementById('lineColorInput'),t=document.getElementById('lineColorText'),w=document.getElementById('lineColorSwatch');function c(v){if(v){i.value=v;t.value=v;w.style.backgroundColor=v}}c(i.value);if(s)s.addEventListener('change',()=>c(s.options[s.selectedIndex].dataset.hex));</script>
@endsection
